# permissions to do viewer virtualhosts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualhost-viewer-role
rules:
- apiGroups:
  - networking.x.k8s.io
  resources:
  - virtualhosts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.x.k8s.io
  resources:
  - virtualhosts/status
  verbs:
  - get
