# permissions to do edit virtualservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualserver-editor-role
rules:
- apiGroups:
  - networking.x.k8s.io
  resources:
  - virtualservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.x.k8s.io
  resources:
  - virtualservers/status
  verbs:
  - get
  - patch
  - update
