# permissions to do viewer virtualservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualserver-viewer-role
rules:
- apiGroups:
  - networking.x.k8s.io
  resources:
  - virtualservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.x.k8s.io
  resources:
  - virtualservers/status
  verbs:
  - get
