kind: GatewayClass
apiVersion: networking.x.k8s.io/v1alpha1
metadata:
  name: acme-tls-lb
controller: acme.io/gateway-controller
parameters:
  apiGroup: networking.acme.io
  kind: AcmeLBConfig
  name: acme-tls-lb-config
---
kind: Gateway
apiVersion: networking.x.k8s.io/v1alpha1
metadata:
  name: my-tls-gateway
  namespace: default
spec:
  class: acme-tls-lb
  listeners:  # Use GatewayClass defaults for listener definition.
    - name: my-tls-listener
      protocol: TCP
      virtualHosts:
        - name: my-tls-example
          tls:
            certificates:
              - group: core
                resource: Secret
                name: my-virtualhost-cert
            minimumVersion: TLS1_3
---
apiVersion: networking.x.k8s.io/v1alpha1
kind: VirtualHost
metadata:
  name: my-tls-example
spec:
  hostnames:
    - my.tls.virtualhost.com
  rules:
    - match:
        path: /bar
      filter:
        headers:
          add:
            my-added-header: foo
          remove:
            - bar
      action:
        forwardTo:
          resource: Service
          group: core
          name: my-tls-service
