kind: GatewayClass
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: acme-lb
spec: 
  controller: acme.io/gateway-controller
  parametersRef:
    name: acme-lb-configmap
---
kind: Gateway
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: my-gateway
  namespace: default
spec:
  class: acme-lb
  listeners:  # Use GatewayClass defaults for listener definition.
  - name: my-http-listener
    protocol: HTTP
  routes:
    namespaceSelector: {}
    routeSelector:
      matchLabels:
        "app": "foo"
---
kind: HTTPRoute
apiVersion: networking.x-k8s.io/v1alpha1
metadata:
  name: http-app-1
  namespace: default
  labels:
    app: foo
spec:
  hosts:
    - hostnames:
        - "foo.com"
    rules:
    - match:
        path: /bar
      actions:
      - forwardTo:
          targetRef:
            name: my-service
